### ISSUE TITLE
Small typo in readme

### ISSUE THREAD

**Issue by Splinter7149** [sazncode/Bing-Rewards#75]
Change:
END_TIME = 24 hour format hour you would like to start the program, if timer is enabled. Defaults to 19, 7 PM

to:
END_TIME = 24 hour format hour you would like to end the program, if timer is enabled. Defaults to 19, 7 PM

**Comment by ericPeel** [comment]
You can submit pull requests by editing the readme yourself, creating a pull request, and the repo owner can update. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
